### PR TITLE
Embed clean in compile recipes to avoid the risk to forget it..

### PR DESCRIPTION
**Pull request by edogaldo**
embed clean in compile recipes to avoid the risk to forget it..

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I think this change would mean every time make is run, it will clean and then rebuild all the files for the specific target

I know this means there will not be the problem with needing to clean between targets, but isn't this at the expense of building the same target straight away.

Perhaps there is some other way to do this, other than forcing make to effectively not check dependencies.

**Comment by edogaldo** [comment]
Well, I think the confidence to have correct object files is well worth the little time more required by the cleanup anyway if you don't agree feel free to cancel the pr (or let me know and I'll cancel it).

**Comment by rogerclarkmelbourne** [comment]
Let me see if there is another solution

**Comment by rogerclarkmelbourne** [comment]
I thought perhaps the definitions in config.h were only used in one file, but it looks like they are used in lots of files

Rather than calling clean to delete the objects, I think .FORCE can be added to the recipe, and this will force it to recompile everything each time.

But a neater solution, is to refactor the code so that there are separate functions to flash the LED and to toggle the disconnect pin.

If those functions were put in a new file called perhaps config.c, then only config.c would need to be recompiled each time (in addition to whichever file has really been changed)

Or there may be another way altogether to do this.

It can't be the first bit of code that needs to be totally changed if the build target changes ;-)

**Comment by edogaldo** [comment]
> Rather than calling clean to delete the objects, I think .FORCE can be added to the recipe, and this will force it to recompile everything each time.

Maybe it's not the case but what if one build requires compiling a file and another build not? Would the .FORCE clause remove the exceeding file when compiling the second build? If not it would be merged into the second build, wouldn't it?

**Comment by rogerclarkmelbourne** [comment]
Not all the files use the definitions in config.h, so one way to do it, is just to FORCE those files to always recompile , and leave the make file to decide about the others.

I think 3 or 4 C files would need to be FORCED

**Comment by rogerclarkmelbourne** [comment]
I'll probably just add the clean target in front of each of the make sequences, this is what Nordic semi do in their GCC makefiles, so if its good enough for a billion dollar company its good enough for me ;-)

**Pull request merged**
