### PR TITLE
add two board support, stebee and generic-b0 

### PR DESCRIPTION
**Pull request by kuwatay**
add 12MHz cristal setup code.
 modify USB DISC control code. (bug in maple original code ?)

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Out of curiosity, whats the USB Disc bug ?

**Comment by kuwatay** [comment]
Hi, Roger-san

in line 44 of usb.c
  SET_REG(GPIO_CR(USB_DISC_BANK,USB_DISC),(GET_REG(GPIO_CR(USB_DISC_BANK,USB_D
ISC)) & crMask(USB_DISC)) | CR_OUTPUT_OD << CR_SHITF(LED_PIN));

This code make USB_DISC pin to OD (opendrain), which have no direct relation t
o LED_PIN. I believe this should be as follows;

  SET_REG(GPIO_CR(USB_DISC_BANK,USB_DISC),(GET_REG(GPIO_CR(USB_DISC_BANK,USB_D
ISC)) & crMask(USB_DISC)) | CR_OUTPUT_OD << CR_SHITF(USB_DISC));

My modification makes STBee board work. The original code didn't.

-Yoshi

BTW, the board is this one. http://strawberry-linux.com/catalog/items?code=321
03

----- Original Message -----
>Date: Wed, 18 Nov 2015 14:38:00 -0800
>From: Roger Clark <notifications@github.com>
>To: rogerclarkmelbourne/STM32duino-bootloader <STM32duino-bootloader@noreply.
github.com>
>Cc: Yoshitaka Kuwata <kuwatay@nifty.com>
>Subject: Re: [STM32duino-bootloader] add two board support, stebee and
> generic-b0  (#2)
>
>
>Out of curiosity, whats the USB Disc bug ?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/rogerclarkmelbourne/STM32duino-bootloader/pull/2#issuecomm
ent-157887638

**Comment by rogerclarkmelbourne** [comment]
Thanks

This looks like a mistake when I cut and pasted some lines, the LED PIN should not be used for the USB disconnect

**Comment by rogerclarkmelbourne** [comment]
Interesting mistake with the LED_PIN instead of USB_DISC.

It actually makes no difference to the binary at all. But this is just a fluke.
As the Control register for each port is split into 2 parts CRL and CRH, the CR_SHITF for the LED PIN on pin 1 and the CR_SHITF for the USB_DISC on 9, return the same value

However its definiately a mistake, so I have fixed it in my repo and also renamed the define to USB_DISC_PIN to more accurately reflect its purpose

Re: Your other changes

Some files you updated in the /flash folder are probably redundant.
I've never changed them. They come from the original Maple Bootloader (via various repo forks).
So I don't really understand what they do.

Anyway. If its OK with your. I'm going to add the 12Mhz Crystal changed in a separate commit, and then add your two new boards.

I'll probably not action your PR as its easier just for me to make the changes manually myself

Thanks

Roger

**Comment by rogerclarkmelbourne** [comment]
OK.

I've added your 2 new boards.

There was one mistake, the copy for pb0 was copying to pe5 not to pb0, so I've fixed it.

I've not updated the /flash/* files as I don't know why they need to be updated

Anyway, if you get chance can you try the bin files for both of these boards

BTW. What is a stbee board ??

**Comment by kuwatay** [comment]
Roger-san, thank you for your update and fix.

For your information, STBee is a famous STM32-based  education board made by a company named "Strawberry Linux".

http://strawberry-linux.com/catalog/items?code=32103

The schematic is in the manual which is located at;

http://strawberry-linux.com/pub/stbee-manual.pdf

I forgot to mention /flash folder. I modified files there to catch up openocd-0.9, which is installed by macports.
I'll resend PR with a set of new script, if you are interested in. I'm working openocd + arm-usb-ocd + generic STM32 boards.
 
-Yoshi

**Comment by rogerclarkmelbourne** [comment]
Hi Yoshi

OK about the OpenOCD problem.

I can update the file manually if you want, as I don't use them, it doesnt really matter what changes you make

Re: OpenOCD

I normally use the bootloader as I can connect the board via USB and dont need an external programmer.
I have 2  x STLink adaptors and I also have J-Link (but I don't use J-Link very much).
I also use the Black Magic Probe (BMP), (see my repo for Blackmagic) as the BMP is directly supported by GDB (and I think it may work with openOCD)

But I mainly use the BMP for some other experiments I'm doing to use the Nordic nRF51822 (generic boards from eBay etc) with the Arduino (using code originally from RedBearLabs in Canada)

BTW. OK about strawberry-linux.com  I have not see this board before.

Most people now seem to use the Maple mini (clone), which was originally designed by LeafLabs (also in Canada), but people also seem to use a variety of other "generic" stm32f103 boards, as Chinese companies seem to make many different types of STM32F103 boards ;-)

**Pull request closed without merging**
