### PR TITLE
stm32f103 mcu can reset itself without pushing the RESET button on the board

### PR DESCRIPTION
**Pull request by smslit**
### /STM32F1:

1. add systemHardReset in the function dfuFinishUpload, so the stm32f103 mcu can reset itself without pushing the RESET button on the board. 
2. only compile with flag generic-pb0(because the led pin on my board is pb0).

### CODE REVIEW

**Comment by smslit** [comment]
I only have one board, and I can only test the generic-pb0 or other with only led and button.So i only compiled with the FLAG "generic-pb0". Please test other FLAGs.

**Comment by rogerclarkmelbourne** [comment]
Can you explain why this change is necessary ?

**Comment by smslit** [comment]
When I complete uploading the program to the board,  I need to press the reset button to make board run the program. So I add this code to make the board reset itself to run then I only need to press the Upload Button in Arduino IDE without pressing the RESET button on board.

**Comment by smslit** [comment]
It's more convenient.For example, if I would made a device for fun based on stm32f103 mcu without RESET button, when i finish uploading program, I need to turn off the device to make it run the new program.  If it can reset itself, it would be wonderful!

**Comment by rogerclarkmelbourne** [comment]
There is some other problem

It should not be necessary to use HardReset

Normal operation is for the bootloader to jump to the code start address, after the DFU upload is complete, The application code then can reset the USB if necessary

I think the change you propose will be detrimental to the thousands of people who are using it in its current mode, as I suspect it will break the functionality they rely on.

**Comment by smslit** [comment]
Okay

**Pull request closed without merging**
