### PR TITLE
Clean Up Tabs and Spaces

### PR DESCRIPTION
**Pull request by GrantM11235**
The whitespaces were a bit of a mess, so I removed all the trailing tabs and spaces, and converted all the tabs to spaces (four per indent level) as that seemed to be the prevailing style, but I can switch to tabs if that is what you prefer.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Just to confirm....

When did you last pull from my repo, as I had to make lot of changes in addition to your last PR, and I don't want everything to get out of sync.

**Comment by GrantM11235** [comment]
Everything is up to date, I rebased to commit d19bcaf1ef044eb5e09b772f7a1d7c158c3c2976 from 5 hours ago.

**Comment by rogerclarkmelbourne** [comment]
OK. Thanks.

That was the last commit I did and it was just to re-instate a timeout.

I'll try to test the PR later.

**Comment by GrantM11235** [comment]
I am also considering getting rid of extra spaces that are used for horizontal alignment, because while it is nice in theory, over time it gets messier and messier if no one is paying special attention to it. What do you think?

untitled

**Comment by GrantM11235** [comment]
Oops, make wasn't happy with spaces instead of tabs in the Makefile, but it is fixed now. I compiled the binaries and compared them to the ones I compiled from the master branch, and they are the same.

**Comment by rogerclarkmelbourne** [comment]
OK.

Makefiles can be picky about this, and they don't like spaces after the end of continuation \'s

**Comment by rogerclarkmelbourne** [comment]
Thanks

I did a test build and git didnt report any difference to the binaries, so I have merged the PR

**Pull request merged**
