### PR TITLE
Unify STM32F1 and GD32F1

### PR DESCRIPTION
**Pull request by GrantM11235**
#26 I think I did it! All targets still compile, and I checked that the binary for the DSO138 still has the same hash as the one from before. I am less confident about the GD32F1 side of things, but I don't have a board to test it on.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks

I'll take a look ( and test on a Blue Pill and a Maple mini)

**Comment by GrantM11235** [comment]
I just checked, and all the other binaries for STM32F1 targets are the same before and after the merge on my compiler. The binaries for the GD32F1 targets are different, though. Most likely due to the changes to hardware.c.

**Comment by rogerclarkmelbourne** [comment]
OK.

Do you have any GD32 boards  to test this?

**Comment by GrantM11235** [comment]
Nope, sorry.

**Comment by rogerclarkmelbourne** [comment]
OK.

I'll need to find one of my boards to test

**Comment by GrantM11235** [comment]
I haven't updated the binaries in the repo yet, so you will need to compile them yourself, or I can send you the new binaries if that is easier. Keep in mind that I renamed the targets in the Makefile to gd32f1-generic-pc13 and gd32-frankenmaple.

**Comment by rogerclarkmelbourne** [comment]
I'll recompile the binaries

**Pull request merged**
