### PR TITLE
Lower stack to 10K point

### PR DESCRIPTION
**Pull request by arpruss**
This PR lowers the stack location to the 10K point in RAM (except in the case of the c_only_md_RAM.ld builds which I don't understand). This makes the bootloader work on devices like the stm32f103c6 (and some fake stm32f103c8 which might be relabeled c6's) that have only 10K RAM.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Ah. OK.

I see what you did. I presume there would need to be a separate version binary, but this would work for both as the bootloader doesn't need 20k of RAM

**Comment by arpruss** [comment]
I think a single binary will work fine for C6, C8 and CB, since the bootloader can run in 10K RAM and 8K flash.

**Comment by rogerclarkmelbourne** [comment]
Yes. Its a good solution.

But I'll need to test it ;-)

**Comment by rogerclarkmelbourne** [comment]
Tested on a blue pill and rebuilt the binaries myself to confirm...

Thanks

**Pull request merged**
